health/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='homeApp')),

]

# handler404 = 'mamtaApp.views.bad_request'
# handler500 = 'mamtaApp.views.bad_server'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import *
from .apiView import *
#
# app_name = 'polls'
urlpatterns = [

    path('', index, name='index'),
    path('registrationformA/',registrationformA,name='registrationformA'),
    path('ApplicantBasicApiView/', ApplicantBasicApiView, name='ApplicantBasicApiView'),
    path('ApplicantPersonEmployeeApiView/', ApplicantPersonEmployeeApiView, name='ApplicantPersonEmployeeApiView'),
    path('DeleteApplicantPersonEmployeeApiView/', DeleteApplicantPersonEmployeeApiView, name='DeleteApplicantPersonEmployeeApiView'),
    path('ApplicantDoctorStaffApiView/', ApplicantDoctorStaffApiView, name='ApplicantDoctorStaffApiView'),
    path('DeleteApplicantDoctorApiView/', DeleteApplicantDoctorApiView, name='DeleteApplicantDoctorApiView'),
    path('ApplicantNurseStaffApiView/', ApplicantNurseStaffApiView, name='ApplicantNurseStaffApiView'),
    path('DeleteApplicantNurseApiView/', DeleteApplicantNurseApiView, name='DeleteApplicantNurseApiView'),
    path('RequestForApplicantApprovalApiView/', RequestForApplicantApprovalApiView, name='RequestForApplicantApprovalApiView'),

    path('applicantDashboard/',applicantDashboard,name='applicantDashboard'),
    path('register_applicant/',register_applicant,name='register_applicant'),
    path('login_applicant/',login_applicant,name='login_applicant'),
    # login
    path('adminLogin/', adminLogin, name='adminLogin'),
    #Logout
    path('logout_user/', logout_user, name='logout_user'),
# --------------------------------RO------------------------------------------------------------
    path('roHome/', roHome, name='roHome'),
    #user
    path('roHome/add_user/', add_user, name='add_user'),
    path('roHome/user_name_exist/', user_name_exist, name='user_name_exist'),
    path('roHome/add_admin_user_post/', add_admin_user_post, name='add_admin_user_post'),
    path('roHome/user_list/', user_list, name='user_list'),
    path('UserListJson/', UserListJson.as_view(), name='UserListJson'),
    path('roHome/pending_list/', pending_list, name='pending_list'),
    path('roHome/approval_list/', approval_list, name='approval_list'),
    path('roHome/RoPendingListJson/', RoPendingListJson.as_view(), name='RoPendingListJson'),
    path('roHome/RoApprovalListJson/', RoApprovalListJson.as_view(), name='RoApprovalListJson'),
    path('roHome/applicant_from_detail_ro/<int:id>/', applicant_form_detail_ro,
         name='applicant_form_detail_Ro'),

    path('roHome/applicant_detail/', applicant_detail, name='applicant_detail'),
    path('roHome/applicant_from_detail/<int:id>/', applicant_form_detail, name='applicant_form_detail'),
    path('roHome/after_verify_applicant_checklist_ro/<int:id>/',
         after_verify_applicant_checklist_ro, name='after_verify_applicant_checklist_ro'),
    path('roHome/approve_and_issue_certificate_to_applicant/',
         approve_and_issue_certificate_to_applicant, name='approve_and_issue_certificate_to_applicant'),

    # ---------------------------------Inspection---------------------------------------------------
    path('inspectionHome/', inspectionHome, name='inspectionHome'),
    path('inspectionPendingList/', inspectionPendingList, name='inspectionPendingList'),
    path('inspectionHome/inspectionPendingListJson/', inspectionPendingListJson.as_view(), name='inspectionPendingListJson'),
    path('inspectionHome/applicant_from_detail/<int:id>/', applicant_form_detail_inspection, name='applicant_form_detail_inspection'),
    path('inspectionHome/verify_applicant_checklist_inspection/<int:id>/', verify_applicant_checklist_inspection, name='verify_applicant_checklist_inspection'),
    path('inspectionHome/after_verify_applicant_checklist_inspection/<int:id>/', after_verify_applicant_checklist_inspection, name='after_verify_applicant_checklist_inspection'),

    path('inspectionHome/submit_checklist_applicant/', submit_checklist_applicant, name='submit_checklist_applicant'),

    path('inspectionHome/inspectionApprovedList/', inspectionApprovedList, name='inspectionApprovedList'),
    path('inspectionHome/inspectionApproveListJson/', inspectionApproveListJson.as_view(), name='inspectionApproveListJson'),


# UPDATE
    path('CheckListOtherDetailsApiView/', CheckListOtherDetailsApiView, name='CheckListOtherDetailsApiView'),
    path('CampusDetailsApiView/', CampusDetailsApiView, name='CampusDetailsApiView'),
# END UPDATE
# 15-03-2021 UPDATE
    path('download_certificate/',download_certificate,name='download_certificate'),
    path('applicantProfile/',applicantProfile,name='applicantProfile'),
    path('applicantChangesPasswordApiView/',applicantChangesPasswordApiView,name='applicantChangesPasswordApiView'),


    path('RenewalPaymentRequestApiView/',RenewalPaymentRequestApiView,name='RenewalPaymentRequestApiView'),
]

home/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User, Group
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django_datatables_view.base_datatable_view import BaseDatatableView
from functools import wraps
from html import escape

import datetime

from weasyprint import HTML, CSS

from .models import *


# Create your views here.
# DataTablebles
# supplier
def check_group(group_name):
    def _check_group(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            if not request.user.groups.filter(name=group_name).exists():
                return redirect('/')
            return view_func(request, *args, **kwargs)

        return wrapper

    return _check_group


class UserListJson(BaseDatatableView):
    order_columns = ['name', 'email', 'password', 'phoneNumber', 'userType', 'action']

    def get_initial_queryset(self):
        return AdminUser.objects.filter(isDeleted__exact=False)

    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(
                Q(name__icontains=search) | Q(password__icontains=search) | Q(email__icontains=search) | Q(
                    userType__icontains=search) | Q(
                    phoneNumber__icontains=search), isDeleted__exact=False)
        return qs

    def prepare_results(self, qs):
        json_data = []
        i = 1
        for item in qs:
            action = ''' <a class="column" data-tooltip="Will be enabled Soon" href="#" style="position: absolute;width: 0px;margin-left: -26px;margin-top: -10px;"><i class="edit outline icon"></i></a>
                         <a class="column"  data-tooltip="Will be enabled Soon" style="position: absolute;width: 0px;margin-left: -6px;margin-top: -10px;" onclick="show_Delete_Models({})"><i class="trash alternate outline icon"></i></a>'''.format(
                item.pk, item.pk)
            json_data.append([
                escape(item.name),  # escape HTML for security reasons
                escape(item.email),
                escape(item.password),
                escape(item.phoneNumber),
                escape(item.userType),
                action
            ])
            i = i + 1
        return json_data


def index(request):
    return render(request, 'home/index.html')


def adminLogin(request):
    if request.method == 'POST':

        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if 'RO' in request.user.groups.values_list('name', flat=True):
                return redirect('/roHome/')
            elif 'Inspection' in request.user.groups.values_list('name', flat=True):
                return redirect('/inspectionHome/')
        else:
            messages.success(request, "Wrong Credential! Please try again.")

            return render(request, "home/admin/adminLogin.html", {})
    return render(request, 'home/admin/adminLogin.html')


def logout_user(request):
    logout(request)
    return redirect('/')


@check_group('RO')
def roHome(request):
    user_count = AdminUser.objects.filter(isDeleted__exact=False).count()
    total = Applicant.objects.filter(isDeleted__exact=False, isDetailCompletelySubmitted__exact=True).count()
    total_p = Applicant.objects.filter(isDeleted__exact=False, isCheckedByInspector__exact=True, isApproved__exact=False,
                                       isDetailCompletelySubmitted__exact=True).count()
    total_v = Applicant.objects.filter(isDeleted__exact=False, isApproved__exact=True,
                                       isDetailCompletelySubmitted__exact=True).count()

    context = {
        'user_count':user_count,
        'total':total,
        'total_p':total_p,
        'total_v':total_v
    }
    return render(request, 'home/admin/roHomepage.html', context)


@check_group('RO')
def add_user(request):
    return render(request, 'home/admin/addUser.html')


@check_group('RO')
def user_name_exist(request, *args, **kwargs):
    username = request.GET.get('q')
    try:

        user = User.objects.get(username__iexact=username)
        return JsonResponse({'message': 'Email already taken. Please try some other name.', 'canUse': 'No'})
    except:
        return JsonResponse({'message': 'Email available.', 'canUse': 'Yes'})


@check_group('RO')
def add_admin_user_post(request):
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            email = request.POST.get('email')
            phone = request.POST.get('phoneNumber')
            userType = request.POST.get('userType')
            password = request.POST.get('password')

            staff = AdminUser()
            staff.name = name
            staff.email = email
            staff.phoneNumber = phone
            staff.password = password
            staff.userType = userType
            new_user = User()
            new_user.username = email
            new_user.set_password(password)
            new_user.save()

            staff.userID_id = new_user.pk
            if userType == 'RO':
                try:
                    g = Group.objects.get(name='RO')
                    g.user_set.add(new_user.pk)
                    g.save()
                except:
                    g = Group()
                    g.name = "RO"
                    g.save()
                    g.user_set.add(new_user.pk)
                    g.save()
            elif userType == 'Inspector':
                try:
                    g = Group.objects.get(name='Inspection')
                    g.user_set.add(new_user.pk)
                    g.save()
                except:
                    g = Group()
                    g.name = "Inspection"
                    g.save()
                    g.user_set.add(new_user.pk)
                    g.save()

            staff.save()

            return redirect('/roHome/user_list/')

        except:
            messages.success(request, 'Error. Please try again.')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@check_group('RO')
def user_list(request):
    return render(request, 'home/admin/userList.html')

@check_group('RO')
def pending_list(request):
    return render(request, 'home/admin/pendingListRo.html')


@check_group('RO')
def approval_list(request):
    return render(request, 'home/admin/approvedListRo.html')


class RoPendingListJson(BaseDatatableView):
    order_columns = ['name','enrollmentNumber','typeOfApplicationCategory','typeOfApplicationSubCategory','datetime']

    def get_initial_queryset(self):
        return Applicant.objects.filter(isDeleted__exact=False, isDetailCompletelySubmitted__exact=True, isCheckedByInspector=True, isApproved__exact=False)

    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(
                Q(name__icontains=search) | Q(enrollmentNumber__icontains=search)| Q(typeOfApplicationCategory__icontains=search)
                |Q(typeOfApplicationSubCategory__icontains=search)|Q(datetime__icontains=search), isDeleted__exact=False)
        return qs
    def prepare_results(self, qs):
        json_data = []
        i = 1
        for item in qs:
            action = ''' <a class="column" data-tooltip="View" href="/roHome/applicant_from_detail_ro/{}/" style="position: absolute;width: 0px;margin-left: -26px;margin-top: -10px;"><i class="file alternate outline icon"></i></a>
                         '''.format(item.pk)

            json_data.append([
                escape(item.name),  # escape HTML for security reasons
                escape(item.enrollmentNumber),
                escape(item.typeOfApplicationCategory),
                escape(item.typeOfApplicationSubCategory),
                escape(item.datetime.strftime('%d-%m-%Y %I:%M %p')),
                action
            ])
            i = i + 1
        return json_data

class RoApprovalListJson(BaseDatatableView):
    order_columns = ['name','enrollmentNumber','typeOfApplicationCategory','typeOfApplicationSubCategory','datetime']

    def get_initial_queryset(self):
        return Applicant.objects.filter(isDeleted__exact=False, isDetailCompletelySubmitted__exact=True, isCheckedByInspector=True, isApproved__exact=True)

    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(
                Q(name__icontains=search) | Q(enrollmentNumber__icontains=search)| Q(typeOfApplicationCategory__icontains=search)
                |Q(typeOfApplicationSubCategory__icontains=search)|Q(datetime__icontains=search), isDeleted__exact=False)
        return qs
    def prepare_results(self, qs):
        json_data = []
        i = 1
        for item in qs:
            action = ''' <a class="column" data-tooltip="View" href="/roHome/applicant_from_detail_ro/{}/" style="position: absolute;width: 0px;margin-left: -26px;margin-top: -10px;"><i class="file alternate outline icon"></i></a>
                         '''.format(item.pk)

            json_data.append([
                escape(item.name),  # escape HTML for security reasons
                escape(item.enrollmentNumber),
                escape(item.typeOfApplicationCategory),
                escape(item.typeOfApplicationSubCategory),
                escape(item.datetime.strftime('%d-%m-%Y %I:%M %p')),
                action
            ])
            i = i + 1
        return json_data


@check_group('RO')

home/templates/home/inspection/inspectionHomepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    {% block title %}
        <title>Inspection - Dashboard</title>
    {% endblock %}
   <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>

    {% block cssandjs %}

        <style>
            .Myfooter {
                background: #1b1c1d !important;
                bottom: 0 !important;
                position: fixed !important;
                right: 0 !important;
                width: 100% !important;
            }

            #AdminOrderTable_filter {
                position: absolute;
                top: 2.5rem;
                right: 1.2rem;
            }

            #AdminOrderTable_wrapper {
                width: 100%;
                margin-top: 0.2rem;
            }

            #ACustomerTable_filter {
                position: absolute;
                top: 2.5rem;
                right: 1.2rem;
            }

            #ACustomerTable_wrapper {
                width: 100%;
                margin-top: 0.2rem;
            }

            .selection.ui.dropdown {
                margin-bottom: 1rem;
            }

            tr {
                cursor: pointer;
                transition: all .25s ease-in-out
            }

            .selected {
                background-color: lightgray;
                font-weight: bold;
                color: black;
            }

            tr:hover, tr.selected {
                background-color: #FFCF8B
            }

            td {
                padding: 5px;
            }
        </style>
    {% endblock %}
{% block customCss %}

{% endblock %}
</head>
<body>

<div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
    <div class="item">
        <div class="header"> <i class="icon home"></i> Home</div>
        <div class="menu">
            <a class="item" href="{% url 'homeApp:inspectionHome' %}">
                <div>
                    <i class="icon tachometer alternate"></i>
                    Dashboard
                </div>
            </a>
        </div>
    </div>
    <div class="item">
        <div class="header">
            <i class="clipboard list icon"></i>
            Applicant
        </div>
        <div class="menu">
            <a class="item" href="{% url 'homeApp:inspectionPendingList' %}">

                <div><i class="clipboard list icon"></i>Pending Applicant</div>
            </a>
            <a class="item" href="{% url 'homeApp:inspectionApprovedList' %}">
                <div><i class="clipboard check icon"></i>Approved Applicant</div>
            </a>

        </div>
    </div>
    {% comment %}<div class="item">
        <div class="header">
            <i class="user icon"></i>
            Admin
        </div>
        <div class="menu">
            <a class="item" href="#">
                <div><i class="cart arrow down icon"></i>Admin Users</div>
            </a>

        </div>
    </div>{% endcomment %}
    <!--Reports-->

    <a href="#" class="item">
        <div>
            <i class="question circle outline icon"></i>
            Helps
        </div>
    </a>

</div>
<!-- sidebar -->
<!-- top nav -->
<nav class="ui top fixed inverted menu">
    <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
            <i class="sidebar icon"></i>
        </a>
        <a href="#" class="header item">
            INSPECTION-DASHBOARD
        </a>
    </div>
    <div class="right menu">
      {% comment %}  <a href="#" class="item">
            <i class="bell icon"></i>
        </a>{% endcomment %}
        <div class="ui dropdown item">
            <i class="user cirlce icon"></i>

            <div class="menu">
             {% comment %}   <a href="#" class="item">
                    <i class="info circle icon"></i> Profile</a>{% endcomment %}
                <a href="{% url 'homeApp:logout_user' %}" class="item">
                    <i class="sign-out icon"></i>
                    Logout
                </a>
            </div>
        </div>
    </div>
</nav>
<!-- top nav -->
<!-- Main Body-->
<div class="pusher">
    <div class="main-content">
        {% block body %}
            <!--Chart Area-->
            <!--Cart Area-->
            <div class="ui grid stackable padded">
               {% comment %} <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header red">
                                <i class="icon user tie"></i>
                            </div>
                            <div class="header">
                                <div class="ui red header">
                                    10
                                </div>
                            </div>
                            <div class="meta">
                                Total User
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui red button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>{% endcomment %}
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header green">
                                <i class="icon user"></i>
                            </div>
                            <div class="header">
                                <div class="ui header green">{{ total }}</div>
                            </div>
                            <div class="meta">
                                Total Applicant
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui green button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header teal">
                                <i class="icon user"></i>
                            </div>
                            <div class="header">
                                <div class="ui teal header">{{ total_v }}</div>
                            </div>
                            <div class="meta">
                                Verified Applicant
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui teal button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header purple">
                                <i class="icon user"></i>
                            </div>
                            <div class="header">
                                <div class="ui purple header">{{ total_p }}</div>
                            </div>
                            <div class="meta">
                                Pending Applicant
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui purple button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Tables Area-->
      {% comment %}      <div class="ui grid stackable padded">
                <div class="eight wide computer eight wide tablet sixteen wide mobile column">
                    <i class="money bill alternate icon"></i>Latest 10 Orders
                    <a href="#"><i class="clipboard icon"></i> All Orders</a>
                    <table class="ui very compact table" id="AdminOrderTable"
                           style="text-align: center; font-size: 14px; width: 100%!important;">
                        <thead>
                        <tr>
                            <th>OrderID</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>DateTime</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="eight wide computer eight wide tablet sixteen wide mobile column">
                    <i class="user friends icon"></i>Latest 10 Registrations
                    <a href="#"> <i class="users icon"></i>All Customers</a>
                    <table class="ui very compact table" id="ACustomerTable"
                           style="text-align: center; font-size: 14px; width: 100%!important;">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Group</th>
                            <th>DateTime</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
{% endcomment %}
        {% endblock %}

    </div>
    <!-- Footer-->

    <!-- End Footer-->
</div>
<!--End Main Body-->

            {% block myjs %}
                <script>
                    $('.dropdown')
                        .dropdown({
                            clearable: true,
                            placeholder: 'any'
                        })
                    ;

                    $(document).ready(function () {
                        $('#AdminOrderTable').DataTable({
                            dom: 'Blfrtip',
                            buttons: [{
                                extend: 'excel',
                                exportOptions: {
                                    columns: [0, 1, 2, 3, 4]
                                }
                            }, {
                                extend: 'print',
                                exportOptions: {
                                    columns: [0, 1, 2, 3, 4]
                                }
                            }
                            ],
                            "columnDefs": [
                                {"name": "orderid", "targets": 0, "orderable": true},
                                {"name": "customerID", "targets": 1, "orderable": true},
                                {"name": "status", "targets": 2, "orderable": true},
                                {"name": "orderDateTime", "targets": 3, "orderable": true},
                                {"name": "subtotal", "targets": 4, "orderable": true},
                                {"name": "action", "targets": 5, "orderable": false},
                            ],
                            aaSorting: [[3, 'desc']],
                            "lengthMenu": [10, 20, 50, 100],
                            "scrollX": true,
                            "pageLength": 10,
                            "processing": true,
                            "serverSide": true,
                            "ajax": "#"
                        });
                        // ...
                    });
                </script>
            {% endblock %}

</body>
</html>